id: A68008FF4
base_file: f0000.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:56:35.411641
  last_modified_at: 2022-06-19 17:56:35.411658
